### ISSUE TITLE
Is there a roadmap for this repo?

### ISSUE THREAD

**Issue by fabiopagoti** [cloudfoundry/cfcd-prep#2]
I came across this new repo and I wonder if there is any kind of roadmap planned to it.

Can anyone here share your ideas about how this repo should be in the future in terms of content?

I believe this will help finding contributors and improve repo.

**Comment by spgreenberg** [comment]
There is not a roadmap other than keep in line with the CFCD Exam domains and competencies: https://training.linuxfoundation.org/certification/cloud-foundry-certified-developer-cfcd/#domains. 

Given the actual test content is protected, the CFCD administrative team will review PRs for applicability. If you want to discuss a potential addition/change before implementing it, feel free to message me directly in the Cloud Foundry slack (sgreenberg).

We will be open sourcing additional training materials in the coming months and contributions there will be straightforward.
